[package]
name = "git-credential-github-keychain"
version = "0.1.0"
authors = ["Jake Wilkins <jakewilkins@github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keyring = "0.9.0"
serde = "1.0.116"
serde_derive = "1.0.116"
serde_json = "1.0"
reqwest = { version = "0.10.8", features = ["blocking", "json"] }
